---
- name: Configure mailicorn on Fedora
  hosts: vagrant
  tasks:
  - name: install misc stuff
    action: yum name=$item state=latest
    with_items:
      - zsh
      - tmux
      - htop
      - git
      - mercurial
      - ack
      - vim-enhanced
