---
- name: Configure mailicorn on Fedora
  hosts: all
  include: elasticsearch.yml
  include: mongodb.yml
  tasks:
  - name: install misc stuff
    action: yum name=$item state=latest
    with_items:
      - zsh
      - tmux
      - htop
      - git
      - mercurial
      - ack
      - vim-enhanced
